config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :attachments, only: [:destroy, :index]
  
  resources :blackouts, except: [:show]

  resources :comments, only: [:create, :destroy]

  resources :emails, only: [:index, :show, :update] do
    collection do
      get 'sent'
      get 'unread'
      get 'mark_all_as_read'
      get 'reply'
      post 'reply', action: "send_reply"
      get 'new_event'
      get 'existing_event'
      get 'weekly'
      post 'weekly', action: "send_weekly"
    end
  end


  resources :email_forms, except: [:show]

  resources :equipment_profiles

  resources :weather

  resources :events do
    member do
      get 'delete_conf'
      get 'finance'
      get 'duplicate'
      resources :applications, controller: 'event_role_applications', only: [:new, :create] do
        get 'confirm'
        get 'deny'
        get 'withdraw'
      end
    end
    collection do
      get 'calendar'
      get 'reference'
      get 'mobile'
      get 'months/:year/:month', action: :month, as: :month
      get 'past'
      get 'incomplete'
      get 'search'
    end
  end

  post 'eventrequest' => 'events#eventrequest'

  post 'joinrequest' => 'join#joinrequest'

  resources :invoices do
    member do
      post 'email'
      get 'email_confirm'
      get 'prettyView'
      get 'duplicate'
    end
  end  

  resources :invoice_items, except: [:show]

  resources :invoice_contacts, except: [:show]

  resources :locations

  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks'
  }

  devise_for :kiosks, skip: :all, skip_helpers: true, controllers: {
    sessions: 'kiosks/sessions'
  }
  devise_scope :kiosk do
    post "/kiosks/sign_in" => "kiosks/sessions#create", as: :kiosk_session
  end

  resources :kiosks do
    member do
      get 'lock'
      get 'unlock'
      get 'reset_password'
    end
  end
  
  resources :members do
    collection do
      get 'tshirts'
      get 'roles'
      get 'choose_filter'
      get 'super_tics'
      post 'super_tics', action: :update_super_tics
      get 'bulk_edit'
      post 'bulk_edit', action: :bulk_update
    end
  end

  resources :organizations

  resources :timecards do
    member do
      get 'view'
    end
  end

  resources :timecard_entries, except: :show

  post 'login' => 'useraccount#login'
  get 'logout' => 'useraccount#logout'
  get 'useraccount/access_denied'

  get 'calendar/generate.:format' => 'events#generate'
  get 'calendar' => 'events#calendar'
  get 'mobile' => 'events#mobile'

  root to: 'events#index'

  post 'slack_ret', to: proc { [200, {}, ['']] }
end

app/models/blackout.rb
class Blackout < ApplicationRecord
  belongs_to :event, optional: true
  
  attr_accessor :with_new_event
  
  validates :startdate, :enddate, presence: true
  validate :chronologicality, :informative
  
  private
    def chronologicality
      errors.add(:enddate, "can't be before Start Date.") if startdate > enddate
    end
    
    def informative
      errors.add(:base, "Blackout must have at least a title or an associated event.") if self.title.blank? and self.event.blank? and not self.with_new_event
    end
end

app/controllers/blackouts_controller.rb
class BlackoutsController < ApplicationController
  load_and_authorize_resource :except => [:create]
  
  def index
    @title = "List of Blackouts"
    @blackouts = @blackouts.order("enddate DESC")
  end

  def new
    @title = "Create a Blackout"
  end

  def create
    @title = "Create a Blackout"
    @blackout = Blackout.new(blackout_params)
    authorize! :create, @blackout
    
    if @blackout.save
      flash[:notice] = "Blackout created successfully."
      redirect_to blackouts_url
    else
      render :new
    end
  end

  def edit
    @title = "Editing Blackout"
  end

  def update
    @title = "Editing Blackout"
    
    if @blackout.update(blackout_params)
      flash[:notice] = "Blackout updated successfully."
      redirect_to blackouts_url
    else
      render :edit
    end
  end

  def destroy
    @blackout.destroy
    flash[:notice] = "Blackout deleted successfully."
    redirect_to blackouts_url
  end
  
  private
    def blackout_params
      params.require(:blackout).permit(:title, :event_id, :startdate, :enddate)
    end
end

app/helpers/blackouts_helper.rb
module BlackoutsHelper
end

app/views/blackouts/_form.html.erb
<% if @blackout.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@blackout.errors.count, "error") %> prohibited
      this blackout from being saved:</h2>
    <ul>
    <% @blackout.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<table class="generic">
  <tr>
    <th class="subheading"><%= f.label :title %>:</th>
    <td><%= f.text_field :title %></td>
  </tr>
  <% if f.object.event %>
    <tr>
      <th class="subheading">Event:</th>
      <td><%= f.object.event.title %></td>
    </tr>
  <% end %>
  <tr>
    <th class="subheading"><%= f.label :startdate, "Period Start" %>:</th>
    <td><%= f.date_select :startdate %></td>
  </tr>
  <tr>
    <th class="subheading"><%= f.label :enddate, "Period End" %>:</th>
    <td><%= f.date_select :enddate %></td>
  </tr>
  <tr>
    <th class="subheading"></th>
    <td><%= f.submit %></td>
  </tr>
</table>

app/views/blackouts/edit.html.erb
<h1>Edit a blackout period</h1>

<%= form_for @blackout do |f| %>
  <%= render :partial => "form", :locals => {f: f} %>
<% end %>

app/views/blackouts/index.html.erb
<h2>Blackouts</h2>
<p>These are the defined blackout periods--the periods which show up as black on minicalendars to indicate that we will not accept any new events on these dates.</p>
<table class="generic">
  <tr>
    <th>Title</th>
    <th>Period Start</th>
    <th>Period End</th>
    <% if can? :update, Blackout or can? :destroy, Blackout %>
      <th></th>
    <% end %>
  </tr>

  <% @blackouts.each do |blackout| %>
    <tr>
      <td>
        <% if not blackout.title.blank? and not blackout.event.blank? %>
          <%= link_to blackout.event.title, blackout.event %> - <%= blackout.title %>
        <% elsif not blackout.event.blank? %>
          <%= link_to blackout.event.title, blackout.event %>
        <% else %>
          <%= blackout.title %>
        <% end %>
      </td>
      <td><%= blackout.startdate.strftime("%b %d, %Y") %></td>
      <td><%= blackout.enddate.strftime("%b %d, %Y") %></td>
      <% if can? :update, Blackout or can? :destroy, Blackout %>
        <td>
          <%= conditional_link_to "edit", edit_blackout_url(blackout), :update, blackout %>
          <%= conditional_link_to_delete "delete", blackout, :destroy, blackout %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<% if can? :create, Blackout %>
  <% content_for :more do %>
    <ul>
      <li><%= link_to "Create blackout period", new_blackout_url %></li>
    </ul>
  <% end %>
<% end %>

app/views/blackouts/new.html.erb
<h1>Create a new blackout period</h1>

<p>Note that this form is only for creating generic blackouts. To create a blackout that is associated with an event, edit that event and click "Create blackout period."</p>

<%= form_for @blackout do |f| %>
  <%= render :partial => "form", :locals => {f: f} %>
<% end %>