config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :attachments, only: [:destroy, :index]
  
  resources :blackouts, except: [:show]

  resources :comments, only: [:create, :destroy]

  resources :emails, only: [:index, :show, :update] do
    collection do
      get 'sent'
      get 'unread'
      get 'mark_all_as_read'
      get 'reply'
      post 'reply', action: "send_reply"
      get 'new_event'
      get 'existing_event'
      get 'weekly'
      post 'weekly', action: "send_weekly"
    end
  end


  resources :email_forms, except: [:show]

  resources :equipment_profiles

  resources :weather

  resources :events do
    member do
      get 'delete_conf'
      get 'finance'
      get 'duplicate'
      resources :applications, controller: 'event_role_applications', only: [:new, :create] do
        get 'confirm'
        get 'deny'
        get 'withdraw'
      end
    end
    collection do
      get 'calendar'
      get 'reference'
      get 'mobile'
      get 'months/:year/:month', action: :month, as: :month
      get 'past'
      get 'incomplete'
      get 'search'
    end
  end

  post 'eventrequest' => 'events#eventrequest'

  post 'joinrequest' => 'join#joinrequest'

  resources :invoices do
    member do
      post 'email'
      get 'email_confirm'
      get 'prettyView'
      get 'duplicate'
    end
  end  

  resources :invoice_items, except: [:show]

  resources :invoice_contacts, except: [:show]

  resources :locations

  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks'
  }

  devise_for :kiosks, skip: :all, skip_helpers: true, controllers: {
    sessions: 'kiosks/sessions'
  }
  devise_scope :kiosk do
    post "/kiosks/sign_in" => "kiosks/sessions#create", as: :kiosk_session
  end

  resources :kiosks do
    member do
      get 'lock'
      get 'unlock'
      get 'reset_password'
    end
  end
  
  resources :members do
    collection do
      get 'tshirts'
      get 'roles'
      get 'choose_filter'
      get 'super_tics'
      post 'super_tics', action: :update_super_tics
      get 'bulk_edit'
      post 'bulk_edit', action: :bulk_update
    end
  end

  resources :organizations

  resources :timecards do
    member do
      get 'view'
    end
  end

  resources :timecard_entries, except: :show

  post 'login' => 'useraccount#login'
  get 'logout' => 'useraccount#logout'
  get 'useraccount/access_denied'

  get 'calendar/generate.:format' => 'events#generate'
  get 'calendar' => 'events#calendar'
  get 'mobile' => 'events#mobile'

  root to: 'events#index'

  post 'slack_ret', to: proc { [200, {}, ['']] }
end

app/models/timecard.rb
class Timecard < ApplicationRecord
  has_many :timecard_entries
  has_many :members, -> { order("namelast ASC").distinct }, :through => :timecard_entries

  validates_presence_of :billing_date, :due_date, :start_date, :end_date
  validates_uniqueness_of :billing_date

  before_destroy :clear_entries

  after_save do |timecard|
    TimecardEntry.where("timecard_id IS NULL").each do |entry|
      entry.timecard = timecard
      entry.save
    end
  end

  def self.valid_eventdates
    timecards = self.valid_timecards
    return Eventdate.where(["startdate >= ? AND events.billable = ?", Account.magic_date, true]).includes(:event).references(:event).sort_by{|ed| ed.event.title} if timecards.size == 0
    start_date, end_date = timecards.inject([nil,nil]) do |pair, timecard|
      [
        ((pair[0].nil? or timecard.start_date < pair[0]) ? timecard.start_date : pair[0]), 
        ((pair[1].nil? or timecard.end_date > pair[1]) ? timecard.end_date : pair[1])
      ]
    end

    Eventdate.where("startdate >= ? AND startdate <= ? AND events.status IN (?) AND events.billable = ?", start_date, end_date, Event::Event_Status_Group_Not_Cancelled, true).order("startdate DESC").includes(:event).references(:event)
  end

  def self.valid_eventdates_and_parts
    dates = self.valid_eventdates
    dates_and_parts = []
    dates.each do |date|
      # In reverse order so appears chronologically with everything else
      dates_and_parts.append({ eventdate: date, eventpart: "strike"}) if date.billable_strike?
      dates_and_parts.append({ eventdate: date, eventpart: "show"}) if date.billable_show?
      dates_and_parts.append({ eventdate: date, eventpart: "call"}) if date.billable_call?
    end
    dates_and_parts
  end

  def entries(member=nil)
    timecard_entries.where(member: member).order("eventdates.startdate ASC").includes(:eventdate).references(:eventdate) unless timecard_entries.nil?
  end

  def hours(member=nil)
    if member
      scope = timecard_entries.where(member: member)
    else
      scope = timecard_entries
    end
    
    if scope.empty?
      0
    else
      scope.map(&:hours).reduce(&:+).round(2)
    end
  end

  def self.latest_dates
    Timecard.order(billing_date: :desc).first
  end

  def self.valid_timecards
    Timecard.where(submitted: false).order("due_date DESC")
  end

  def clear_entries
    timecard_entries.each do |entry|
      entry.timecard = nil
      entry.save
    end
  end

  def valid_eventdates
    Eventdate.where("startdate >= ? AND startdate <= ? AND events.billable = ?", start_date, end_date, true).includes(:event).references(:event)
  end

  def valid_eventdates_and_parts
    dates = valid_eventdates
    dates_and_parts = []
    dates.each do |date|
      # In reverse order so appears chronologically with everything else
      dates_and_parts.append({ eventdate: date, eventpart: "strike"}) if date.billable_strike
      dates_and_parts.append({ eventdate: date, eventpart: "show"}) if date.billable_show
      dates_and_parts.append({ eventdate: date, eventpart: "call"}) if date.billable_call
    end
    dates_and_parts
  end
end

app/controllers/timecard_controller.rb
class TimecardController < ApplicationController
	before_filter :login_required
	layout 'application2'

	def index
		@timecard_entries = TimecardEntry.find(:all)
	end

	def new
		@timecard_entry = TimecardEntry.new
		@timecard_entry.event_id = params[:event_id]
		@events = TimecardEntry.valid_events.collect { |e| [e.title, e.id]}
	end

	def create
		@timecard_entry = TimecardEntry.new(params[:timecard_entry])
		@timecard_entry.member = current_member
		puts @timecard_entry
		if @timecard_entry.save
			flash[:notice] = "Timecard entry saved"
			redirect_to :action => :index
		else
			flash[:notice] = "Error saving entry"
			@events = TimecardEntry.valid_events.collect { |e| [e.title, e.id]}
			render :action => :new
		end
	end

	def show
	end
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  load_and_authorize_resource :except => :create
  
  def index
    @timecards = @timecards.order("billing_date DESC")
  end

  def show
    @member = current_member
    @past = current_member.timecards.where(submitted: true)
  end

  def view
  end

  def new
    interval = 1.week
    if not Timecard.latest_dates.nil?
      @timecard.billing_date = Timecard.latest_dates.billing_date + interval
      @timecard.due_date = Timecard.latest_dates.due_date + interval
      @timecard.start_date = Timecard.latest_dates.start_date + interval
      @timecard.end_date = Timecard.latest_dates.end_date + interval
    else
      @timecard.billing_date = Date.today + interval
      @timecard.due_date = Date.today + interval
      @timecard.start_date = Date.today
      @timecard.end_date = Date.today + interval
    end
  end

  def create
    @timecard = Timecard.new(timecard_params)
    authorize! :create, @timecard
    
    if @timecard.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @timecard.update(timecard_params)
      flash[:notice] = 'Timecard updated successfully'
      redirect_to :action => 'view'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @timecard.destroy
    redirect_to :action => 'index'
  end
  
  private
    def timecard_params
      params.require(:timecard).permit(:billing_date, :due_date, :start_date, :end_date, :submitted)
    end
end

app/helpers/timecards_helper.rb
module TimecardsHelper
  def format_timecard_date( date )
    date.strftime("%m/%d/%y")
  end

  def format_time(hours)
    sprintf("%2d:%02d",hours.to_i, (hours*60)%60)
  end

  def timecards_for_select(past)
    past.map do |timecard|
      [timecard.billing_date.strftime("%b %d %Y"), timecard_url(timecard)]
    end
  end
end

app/views/timecards/_form.html.erb
<table class="generic">
<tr><td>Billing Date:</td><td><%= date_select :timecard, :billing_date %></td><td>This is the pay period end date that is printed on the timecard. This field defaults to 1 week after the previous billing date.</td></tr>
<tr><td>Due Date:</td><td><%= date_select :timecard, :due_date %></td><td>The date printed on the timecard indicating when it is due, usually a Friday. This field defaults to 1 week after the previous due date.</td></tr>
<tr><td>Start Date:</td><td><%= date_select :timecard, :start_date %></td><td>This date is used to determine what events are valid to be billed on this timecard: only events that start after this date are included. This defaults to 1 week after the previous start date.</tr>
<tr><td>End Date:</td><td><%= date_select :timecard, :end_date %></td><td>Only events that start before the beginning of this date are valid for this timecard. This defaults to 1 week after the previous timecard's end date.</tr>
</table>

app/views/timecards/_timecard.html.erb
<% if details %>
  <p>
    This timecard is for the period ending on
    <%= timecard.billing_date.strftime("%b %d, %Y") %> and
    <% timecard.submitted? ? "was" : "is" %> due on
    <%= timecard.due_date.strftime("%b %d, %Y") %>.
    This timecard is only for events between <%= timecard.start_date.strftime("%b %d") %> and <%= timecard.end_date.strftime("%b %d") %>.
  </p>
<% end %>

<table class="generic" border="1">
  <tr>
    <th>Event</th> <th>Start Date/Time</th> <th>Hours</th> <% unless !details or timecard.submitted or timecard.entries(member).empty? %><th></th><% end %>
  </tr>

  <% timecard.entries(member).each do |t| %>
    <tr>
      <%= render :partial => 'timecard_entries/timecard_entry', :object => t %>
      <% unless !details or timecard.submitted %>
        <td>
          <%= link_to 'Edit', edit_timecard_entry_path(t) %>
          <%= link_to 'Destroy', timecard_entry_path(t), :method => 'delete', data: {confirm: "Are you sure?"} %>
        </td>
      <% end %>
    </tr>
  <% end %>
  <tfoot>
    <tr>
      <td><strong>Total</strong></td>
      <td></td>
      <td><%= timecard.entries(member).map(&:hours).reduce(0.0, &:+).round(2) %></td>
      <% unless timecard.entries(member).empty? %><th></th><% end %>
    </tr>
  </tfoot>
</table>

app/views/timecards/edit.html.erb
<% @title = 'Edit timecard' %>
<h1>Update Timecard</h1>
<p>
  <% if @timecard.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@timecard.errors.count, "error") %> prohibited
        this timecard from being saved:</h2>
      <ul>
      <% @timecard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</p>
<%= form_tag timecard_path(@timecard), :method => 'put' do |f| %>
  <%= render :partial => 'form' %>
  <p>Submitted? <%= check_box :timecard, :submitted %></p>
  <%= submit_tag 'Update' %>
<% end %>

app/views/timecards/index.html.erb
<% @title = 'Timecards' %>
<h1>Timecards</h1>
<div>
<p>To prevent members from editing entries for a timecard, edit the
timecard and check the 'submitted' checkbox. The 'View all details' link
allows you to see the entries that everyone has submitted.</p>
</div>
<table class="generic" border="1">
<tr>
<th>Billing date</th>
<th>Due date</th>
<th>Total hours billed</th>
<th>Submitted</th>
<% if can? :view, Timecard or can? :update, Timecard or can? :destroy, Timecard %>
  <th>&nbsp;</th>
<% end %>
</tr>
<% @timecards.each do |timecard| %>
<tr>
<td><%= timecard.billing_date.strftime "%b %d, %Y" %></td>
<td><%= timecard.due_date.strftime "%b %d, %Y" %></td>
<td><%= timecard.hours %></td>
<td><%= timecard.submitted ? 'yes' : 'no' %></td>
<% if can? :view, Timecard or can? :update, Timecard or can? :destroy, Timecard %>
<td>
	<%= conditional_link_to 'View all details', view_timecard_url(timecard), :view, timecard %>
	<%= conditional_link_to 'Edit', edit_timecard_url(timecard), :update, timecard %>
	<%= link_to 'Destroy', timecard_url(timecard), :method => 'delete', data: { confirm: "Are you sure?" } if can? :destroy, timecard %>
</td>
<% end %>
</tr>
<% end %>
</table>

<% if can? :create, Timecard %>
  <% content_for :more do %>
    <ul>
      <li><%= link_to "Create a new timecard", new_timecard_path %></li>
    </ul>
  <% end %>
<% end %>

app/views/timecards/new.html.erb
<% @title = 'New timecard' %>
<h1>Create new Timecard</h1>
<p>
  <% if @timecard.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@timecard.errors.count, "error") %> prohibited
        this timecard from being saved:</h2>
      <ul>
      <% @timecard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</p>
<%= form_for @timecard, :url => {:action => :create} do |f| %>
  <%= render :partial => 'form' %>
  <%= submit_tag 'Create' %>
<% end %>

app/views/timecards/show.html.erb
<% @title = 'Viewing Timecard' %>
<h1>Showing timecard</h1>
<%= render :partial => 'timecard', :object => @timecard, :locals => {:member => @member, :details => true} %>

<% content_for :more do %>
  <ul>
    <li>View <%= link_to 'current timecard', timecard_entries_path %></li>
  </ul>
<% end %>

<% if not @past.empty? %>
  <% content_for :extra do %>
    <div class="event-box">
      <h4>Submitted timecards</h4>

      <%= select_tag :timecard_selection, options_for_select(timecards_for_select(@past.reverse)), id: "timecard-dropdown", :include_blank => 'select' %>
    </div>
  <% end %>
<% end %>

app/views/timecards/view.html.erb
<% @title = 'Viewing timecard details' %>
<h1>Showing timecard</h1>
<p>This timecard is for the billing period ending on <%= @timecard.billing_date.strftime("%b %d, %Y") %> and <% if @timecard.submitted %>was<% else %>is<% end %> due on <%= @timecard.due_date.strftime("%b %d, %Y") %>.</p>

<% @timecard.members.each do |member| %>
  <h2>Timecard for <%= text_with_conditional_link_to member.fullname, member, :read, member %> (<%= number_to_currency member.payrate %>/hr)</h2>
<%= render :partial => 'timecard', :object => @timecard, :locals => {:member => member, :details => false} %>
<% end %>

<% content_for :more do %>
  <ul>
    <li><%= link_to "Back to list of timecards", timecards_path %></li>
  </ul>
<% end %>