config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :attachments, only: [:destroy, :index]
  
  resources :blackouts, except: [:show]

  resources :comments, only: [:create, :destroy]

  resources :emails, only: [:index, :show, :update] do
    collection do
      get 'sent'
      get 'unread'
      get 'mark_all_as_read'
      get 'reply'
      post 'reply', action: "send_reply"
      get 'new_event'
      get 'existing_event'
      get 'weekly'
      post 'weekly', action: "send_weekly"
    end
  end


  resources :email_forms, except: [:show]

  resources :equipment_profiles

  resources :weather

  resources :events do
    member do
      get 'delete_conf'
      get 'finance'
      get 'duplicate'
      resources :applications, controller: 'event_role_applications', only: [:new, :create] do
        get 'confirm'
        get 'deny'
        get 'withdraw'
      end
    end
    collection do
      get 'calendar'
      get 'reference'
      get 'mobile'
      get 'months/:year/:month', action: :month, as: :month
      get 'past'
      get 'incomplete'
      get 'search'
    end
  end

  post 'eventrequest' => 'events#eventrequest'

  post 'joinrequest' => 'join#joinrequest'

  resources :invoices do
    member do
      post 'email'
      get 'email_confirm'
      get 'prettyView'
      get 'duplicate'
    end
  end  

  resources :invoice_items, except: [:show]

  resources :invoice_contacts, except: [:show]

  resources :locations

  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks'
  }

  devise_for :kiosks, skip: :all, skip_helpers: true, controllers: {
    sessions: 'kiosks/sessions'
  }
  devise_scope :kiosk do
    post "/kiosks/sign_in" => "kiosks/sessions#create", as: :kiosk_session
  end

  resources :kiosks do
    member do
      get 'lock'
      get 'unlock'
      get 'reset_password'
    end
  end
  
  resources :members do
    collection do
      get 'tshirts'
      get 'roles'
      get 'choose_filter'
      get 'super_tics'
      post 'super_tics', action: :update_super_tics
      get 'bulk_edit'
      post 'bulk_edit', action: :bulk_update
    end
  end

  resources :organizations

  resources :timecards do
    member do
      get 'view'
    end
  end

  resources :timecard_entries, except: :show

  post 'login' => 'useraccount#login'
  get 'logout' => 'useraccount#logout'
  get 'useraccount/access_denied'

  get 'calendar/generate.:format' => 'events#generate'
  get 'calendar' => 'events#calendar'
  get 'mobile' => 'events#mobile'

  root to: 'events#index'

  post 'slack_ret', to: proc { [200, {}, ['']] }
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  validates_presence_of :memo, :category, :price, :corporate
  validates_inclusion_of :category, :in => InvoiceLine::Invoice_Categories
  validates_numericality_of :price, :corporate
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  load_and_authorize_resource :except => [:create]

  def index
    @title = "Invoice Line Presets"
  end

  def new
    @title = "Create a new Invoice Line Preset"
  end

  def create
    @title = "Create a new Invoice Line Preset"
    @invoice_item = InvoiceItem.new(ii_params)
    authorize! :create, @invoice_item
    
    if @invoice_item.save
      flash[:notice] = 'Invoice item was successfully created.'
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @title = "Edit Invoice Line Preset"
  end

  def update
    @title = "Edit Invoice Line Preset"
    
    if @invoice_item.update(ii_params)
      flash[:notice] = 'Invoice item was successfully updated.'
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @invoice_item.destroy
    flash[:notice] = 'Invoice item was successfully deleted.'
    redirect_to :action => 'index'
  end
  
  private
    def ii_params
      params.require(:invoice_item).permit(:memo, :category, :price, :notes, :line_no)
    end
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/views/invoice_items/_form.html.erb
<% if @invoice_item.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@invoice_item.errors.count, "error") %> prohibited
      this invoice item from being saved:</h2>
    <ul>
    <% @invoice_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<table class="generic">
  <tr>
    <td class="subheading"><%= f.label :memo %>:</td>
    <td><%= f.text_field :memo, size: 50 %></td>
  </tr>
  <tr>
    <td class="subheading"><%= f.label :category %>:</td>
    <td><%= f.select :category, InvoiceLine::Invoice_Categories %></td>
  </tr>
  <tr>
    <td class="subheading"><%= f.label :price %>:</td>
    <td><%= f.text_field :price %></td>
  </tr>
  <tr>
    <td class="subheading"><%= f.label :notes %>:</td>
    <td><%= f.text_area :notes, :size => "35x3" %></td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.submit %></td>
  </tr>
</table>

app/views/invoice_items/edit.html.erb
<h1>Editing invoice item</h1>

<%= form_for @invoice_item do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<% content_for :more do %>
  <ul>
    <li><%= link_to 'Back to invoice items list', invoice_items_url %></li>
  </ul>
<% end %>

app/views/invoice_items/index.html.erb
<h1>Listing Invoice Items</h1>
<p>These prices represent default values for creating new invoices. They should be set appropriately to encourage consistent quoting, but they need not be used in all cases. Each event has its own unique set of circumstances and must be priced out accordingly.</p>
<table class="generic">
  <tr>
    <th>Memo</th>
    <th>Category</th>
    <th>Price</th>
    <th>Notes</th>
    <% if can? :update, InvoiceItem %>
      <th></th>
    <% end %>
    <% if can? :destroy, InvoiceItem %>
      <th></th>
    <% end %>
  </tr>
  
<% @invoice_items.each do |item| %>
  <tr>
    <td><%= item.memo %></td>
    <td><%= item.category %></td>
    <td><%= number_to_currency item.price %></td>
    <td><%= simple_format item.notes %></td>
    <% if can? :update, item %>
      <td><%= link_to 'Edit', edit_invoice_item_url(item) %></td>
    <% end %>
    <% if can? :destroy, item %>
      <td><%= link_to 'Destroy', item, data: {confirm: "Are you sure?"}, :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, InvoiceItem %>
  <% content_for :more do %>
    <ul>
      <li><%= link_to 'New invoice item', :action => 'new' %></li>
    </ul>
  <% end %>
<% end %>

app/views/invoice_items/list.html.erb
<h1>Listing Invoice Items</h1>
<p>These prices represent default values for creating new invoices. They should be set appropriately to encourage consistent quoting, but they need not be used in all cases. Each event has its own unique set of circumstances and must be priced out accordingly.</p>
<table class="generic">
  <tr>
    <th>Memo</th>
    <th>Category</th>
    <th>Price recognized</th>
    <th>Price unrecognized</th>
    <th></th>
    <th></th>
  </tr>
  
<% @invoice_items.each do |item| %>
  <tr>
    <td><%= item.memo %></td>
    <td><%= item.category %></td>
    <td><%= number_to_currency item.price_recognized %></td>
    <td><%= number_to_currency item.price_unrecognized %></td>
    <td><%= link_to 'Edit', edit_invoice_item_url(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% content_for :more do %>
  <li><%= link_to 'New invoice item', :action => 'new' %></li>
<% end %>

app/views/invoice_items/new.html.erb
<h1>Creating new invoice item</h1>

<%= form_for @invoice_item do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<% content_for :more do %>
  <ul>
    <li><%= link_to 'Back to invoice items list', invoice_items_url %></li>
  </ul>
<% end %>