config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :attachments, only: [:destroy, :index]
  
  resources :blackouts, except: [:show]

  resources :comments, only: [:create, :destroy]

  resources :emails, only: [:index, :show, :update] do
    collection do
      get 'sent'
      get 'unread'
      get 'mark_all_as_read'
      get 'reply'
      post 'reply', action: "send_reply"
      get 'new_event'
      get 'existing_event'
      get 'weekly'
      post 'weekly', action: "send_weekly"
    end
  end


  resources :email_forms, except: [:show]

  resources :equipment_profiles

  resources :weather

  resources :events do
    member do
      get 'delete_conf'
      get 'finance'
      get 'duplicate'
      resources :applications, controller: 'event_role_applications', only: [:new, :create] do
        get 'confirm'
        get 'deny'
        get 'withdraw'
      end
    end
    collection do
      get 'calendar'
      get 'reference'
      get 'mobile'
      get 'months/:year/:month', action: :month, as: :month
      get 'past'
      get 'incomplete'
      get 'search'
    end
  end

  post 'eventrequest' => 'events#eventrequest'

  post 'joinrequest' => 'join#joinrequest'

  resources :invoices do
    member do
      post 'email'
      get 'email_confirm'
      get 'prettyView'
      get 'duplicate'
    end
  end  

  resources :invoice_items, except: [:show]

  resources :invoice_contacts, except: [:show]

  resources :locations

  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks'
  }

  devise_for :kiosks, skip: :all, skip_helpers: true, controllers: {
    sessions: 'kiosks/sessions'
  }
  devise_scope :kiosk do
    post "/kiosks/sign_in" => "kiosks/sessions#create", as: :kiosk_session
  end

  resources :kiosks do
    member do
      get 'lock'
      get 'unlock'
      get 'reset_password'
    end
  end
  
  resources :members do
    collection do
      get 'tshirts'
      get 'roles'
      get 'choose_filter'
      get 'super_tics'
      post 'super_tics', action: :update_super_tics
      get 'bulk_edit'
      post 'bulk_edit', action: :bulk_update
    end
  end

  resources :organizations

  resources :timecards do
    member do
      get 'view'
    end
  end

  resources :timecard_entries, except: :show

  post 'login' => 'useraccount#login'
  get 'logout' => 'useraccount#logout'
  get 'useraccount/access_denied'

  get 'calendar/generate.:format' => 'events#generate'
  get 'calendar' => 'events#calendar'
  get 'mobile' => 'events#mobile'

  root to: 'events#index'

  post 'slack_ret', to: proc { [200, {}, ['']] }
end

app/models/kiosk.rb
class Kiosk < ApplicationRecord
  devise :database_authenticatable, :lockable, :trackable,
  lock_strategy: :failed_attempts,
  maximum_attempts: 1, unlock_strategy: :none,
  send_email_changed_notification: false, send_password_change_notification: false,
  authentication_keys: [:hostname]  # instead of email

  validates :hostname, presence: true

  def ability
    @ability ||= KioskAbility.new(self)
  end
end

app/controllers/kiosks/sessions_controller.rb
class Kiosks::SessionsController < Devise::SessionsController
    protect_from_forgery except: :create
 end

app/controllers/kiosks_controller.rb
class KiosksController < ApplicationController
  def index
    authorize! :read, Kiosk
    @title = "Kiosks"
    @kiosks = Kiosk.order("hostname ASC")
  end

  def show
    @kiosk = Kiosk.find(params[:id])
    authorize! :read, @kiosk
    @title = "Viewing Kiosk"
  end

  def new
    authorize! :create, Kiosk
    @title = "New Kiosk"
    @kiosk = Kiosk.new
  end

  def create
    authorize! :create, Kiosk
    @kiosk = Kiosk.new(kiosk_params)
    @kiosk.password = SecureRandom.base64(16)
    if @kiosk.save
      flash[:notice] = 'Kiosk created successfully: ' + @kiosk.password
      redirect_to @kiosk
    else
      render(:action => 'new')
    end
  end

  def edit
    @kiosk = Kiosk.find(params[:id])
    authorize! :update, @kiosk
    @title = "Editing Kiosk"
  end

  def update
    @kiosk = Kiosk.find(params[:id])
    authorize! :update, @kiosk
    if @kiosk.update(kiosk_params)
      flash[:notice] = 'Kiosk updated successfully.'
      redirect_to @kiosk
    else
      render(:action => 'edit')
    end
  end

  def destroy
    @kiosk = Kiosk.find(params[:id])
    authorize! :destroy, @kiosk
    @kiosk.destroy
    flash[:notice] = "Kiosk deleted successfully."
    redirect_to kiosks_url
  end

  def lock
    @kiosk = Kiosk.find(params[:id])
    authorize! :lock, @kiosk
    @kiosk.lock_access!
    flash[:notice] = "Kiosk locked successfully."
    redirect_to @kiosk
  end

  def unlock
    @kiosk = Kiosk.find(params[:id])
    authorize! :unlock, @kiosk
    @kiosk.unlock_access!
    flash[:notice] = "Kiosk unlocked successfully."
    redirect_to @kiosk
  end

  def reset_password
    @kiosk = Kiosk.find(params[:id])
    authorize! :update, @kiosk
    password = SecureRandom.base64(16)
    @kiosk.update_attribute(:password, password)
    flash[:notice] = 'Kiosk updated successfully: ' + password
    redirect_to @kiosk
  end

  private
    def kiosk_params
      params.require(:kiosk).permit(:hostname, :show_header_time, :show_header_network_status, :ability_read_equipment, :ability_index_weather)
    end
end

app/helpers/kiosks_helper.rb
module KiosksHelper
end

app/views/kiosks/_form.html.erb
<% if @kiosk.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@kiosk.errors.count, "error") %> prohibited
      this kiosk from being saved:</h2>
    <ul>
    <% @kiosk.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<table class="generic" width="50%">
  <tr>
    <td class="subheading"><%= f.label :hostname %>:</th>
    <td><%= f.text_field :hostname, size: "100%" %></td>
  </tr>
  <tr>
    <td class="subheading"><%= f.label :show_header_time %>:</th>
    <td><%= f.check_box :show_header_time %></td>
  </tr>
  <tr>
    <td class="subheading"><%= f.label :show_header_network_status %>:</th>
    <td><%= f.check_box :show_header_network_status %></td>
  </tr>
  <tr>
    <td class="subheading"><%= f.label :ability_read_equipment %>:</th>
    <td><%= f.check_box :ability_read_equipment %></td>
  </tr>
  <tr>
    <td class="subheading"><%= f.label :ability_index_weather %>:</th>
    <td><%= f.check_box :ability_index_weather %></td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.submit %></td>
  </tr>
</table>

app/views/kiosks/edit.html.erb
<h1>Edit a kiosk</h1>

<%= form_for @kiosk do |f| %>
  <%= render :partial => "form", :locals => {f: f} %>
<% end %>

<% content_for :more do %>
  <ul>
    <li><%= link_to 'Show kiosk', @kiosk %></li>
    <li><%= link_to 'Back to kiosks list', kiosks_path %></li>
  </ul>
<% end %>

app/views/kiosks/index.html.erb
<h1>Kiosks</h1>

<table class="generic">
  <tr>
    <th>Hostname</th>
    <th>Locked</th>
    <% if can? :update, Kiosk or can? :read, Kiosk or can? :destroy, Kiosk or can? :lock, Kiosk or can? :unlock, Kiosk %>
      <th></th>
    <% end %>
  </tr>

  <% for kiosk in @kiosks %>
    <tr>
      <td><%= kiosk.hostname %></td>
      <td><%= kiosk.access_locked? %></td>
      <% if can? :update, Kiosk or can? :read, Kiosk or can? :destroy, Kiosk or can? :lock, Kiosk or can? :unlock, Kiosk %>
        <td>
          <%= conditional_link_to "Show", kiosk_url(kiosk), :read, kiosk %>
          <%= conditional_link_to "Edit", edit_kiosk_url(kiosk), :update, kiosk %>
          <% if can? :update, kiosk %>
            <%= link_to "Reset Password", reset_password_kiosk_url(kiosk), data: {confirm: "Are you sure?"} %>
          <% end %>
          <% if kiosk.access_locked? %>
            <% if can? :unlock, kiosk %>
              <%= link_to "Unlock", unlock_kiosk_url(kiosk), data: {confirm: "Are you sure?"} %>
            <% end %>
          <% else %>
            <% if can? :lock, kiosk %>
              <%= link_to "Lock", lock_kiosk_url(kiosk), data: {confirm: "Are you sure?"} %>
            <% end %>
          <% end %>
          <%= conditional_link_to_delete "Delete", kiosk, :destroy, kiosk %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<% if can? :create, Kiosk %>
  <% content_for :more do %>
    <ul>
      <li><%= link_to "Create kiosk", new_kiosk_url %></li>
    </ul>
  <% end %>
<% end %>

app/views/kiosks/new.html.erb
<h1>New kiosk</h1>

<%= form_for @kiosk do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

<% content_for :more do %>
  <ul>
    <li><%= link_to 'Back to kiosks list', kiosks_path %></li>
  </ul>
<% end %>

app/views/kiosks/show.html.erb
<h2><%= @kiosk.hostname %></h2>

<table class="generic" width="50%">
  <tr>
    <td class="subheading">Hostname:</th>
    <td><%= @kiosk.hostname %></td>
  </tr>
  <tr>
    <td class="subheading">Show Header Time:</th>
    <td><%= @kiosk.show_header_time %></td>
  </tr>
  <tr>
    <td class="subheading">Show Header Network Status:</th>
    <td><%= @kiosk.show_header_network_status %></td>
  </tr>
  <tr>
    <td class="subheading">Ability Read Equipment:</th>
    <td><%= @kiosk.ability_read_equipment %></td>
  </tr>
  <tr>
    <td class="subheading">Ability Index Weather:</th>
    <td><%= @kiosk.ability_index_weather %></td>
  </tr>
  <tr>
    <td class="subheading">Locked:</td>
    <td><%= @kiosk.access_locked? %></td>
  </tr>
  <tr>
    <td class="subheading">Locked at:</td>
    <td><%= @kiosk.locked_at %></td>
  </tr>
  <tr>
    <td class="subheading">Failed auth attempts (since last unlock):</td>
    <td><%= @kiosk.failed_attempts %></td>
  </tr>
  <tr>
    <td class="subheading">Total sign in count:</td>
    <td><%= @kiosk.sign_in_count %></td>
  </tr>
  <tr>
    <td class="subheading">Current sign in at:</td>
    <td><%= @kiosk.current_sign_in_at %></td>
  </tr>
  <tr>
    <td class="subheading">Current sign in IP:</td>
    <td><%= @kiosk.current_sign_in_ip %></td>
  </tr>
  <tr>
    <td class="subheading">Last sign in at:</td>
    <td><%= @kiosk.last_sign_in_at %></td>
  </tr>
  <tr>
    <td class="subheading">Last sign in IP:</td>
    <td><%= @kiosk.last_sign_in_ip %></td>
  </tr>
</table>

<% if can? :update, @kiosk %>
  <%= link_to 'Edit', edit_kiosk_url(@kiosk) %> |
  <%= link_to "Reset Password", reset_password_kiosk_url(@kiosk), data: {confirm: "Are you sure?"} %> |
<% end %>
<% if @kiosk.access_locked? %>
  <% if can? :unlock, @kiosk %>
    <%= link_to "Unlock", unlock_kiosk_url(@kiosk), data: {confirm: "Are you sure?"} %> |
  <% end %>
<% else %>
  <% if can? :lock, @kiosk %>
    <%= link_to "Lock", lock_kiosk_url(@kiosk), data: {confirm: "Are you sure?"} %> |
  <% end %>
<% end %>
<% if can? :destroy, @kiosk %>
  <%= conditional_link_to_delete "Delete", @kiosk, :destroy, @kiosk %> |
<% end %>
<%= link_to 'Back', kiosks_path %>